# this specifies the set of objects we want k8s to look at, deployment belongs to bucket v1
apiVersion: apps/v1
# the type of object we want to create
kind: Deployment
# config options for the object about to create
metadata:
  name: client-depl
# The exact attributes we want to apply to the object we are about to create
spec:
  # number of pods we want to create
  replicas: 1
  selector:
    matchLabels:
      app: client
  # specify the exact configuration of a pod that we want this deployment to create
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          # kubernetes will by default go to Docker hub and look for docker image if no version is specified
          image: hoffmanshf/mini-client
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
