# this specifies the set of objects we want k8s to look at, deployment belongs to bucket v1
apiVersion: v1
# the type of object we want to create
kind: Service
# config options for the object about to create
metadata:
  name: posts-srv
# The exact attributes we want to apply to the object we are about to create
spec:
  type: NodePort
  # selector will find all pods with label of app: posts
  selector:
    app: posts
  # list all the pods we want to expose
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      # actual port the application is listening for traffic on
      targetPort: 4000
